name: web3dart_get_fee_data
description: A Dart package for getting Ethereum fee data, including support for EIP-1559 transactions. Provides an easy-to-use API similar to ethers.js getFeeData().
version: 1.1.0
homepage: https://github.com/quoclewkm/web3dart_get_fee_data
repository: https://github.com/quoclewkm/web3dart_get_fee_data

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  web3dart: ^3.0.1
  http: ^1.4.0
  wallet: ^0.0.18

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2

topics:
  - ethereum
  - web3
  - blockchain
  - gas
  - eip-1559
